"""
Nirikshak AI — Response Builder
===================================
Composes grounded natural-language answers from evidence packages.
Template-based — no generative hallucination.
"""

from typing import List, Dict, Any, Optional
from backend.assistant.schemas import EvidenceItem, DataSnapshot
from backend.assistant.normalizer import format_currency, format_number


DISCLAIMER = (
    "This is an anomaly signal generated by Nirikshak AI's analytical models. "
    "It requires authorized human verification before any action is taken."
)

DISCLAIMER_SHORT = "Anomaly signal — requires human verification."

NO_DATA_MSG = (
    "That information is not available in the current precomputed "
    "Nirikshak AI analytics snapshot."
)

NO_MATCH_MSG = (
    "I could not find a matching record in the current "
    "Nirikshak AI analytics snapshot."
)


def snapshot_msg(timestamp: Optional[str]) -> str:
    if timestamp:
        return (
            f"My response is based on the latest precomputed "
            f"Nirikshak AI analytics snapshot dated {timestamp}."
        )
    return "My response is based on the latest precomputed Nirikshak AI analytics snapshot."


# ─── Evidence Builders ───────────────────────────────────────────────────────

def build_evidence(
    label: str,
    value: Any,
    source: str,
    record_id: Optional[str] = None,
) -> EvidenceItem:
    """Create a single evidence item."""
    return EvidenceItem(
        label=label,
        value=str(value) if value is not None else "N/A",
        source=source,
        record_id=str(record_id) if record_id else None,
    )


# ─── Project Risk Response ──────────────────────────────────────────────────

def build_project_risk_response(
    work_record: Dict,
    finguard_record: Optional[Dict] = None,
    dup_records: Optional[List[Dict]] = None,
    cost_delay_record: Optional[Dict] = None,
    snapshot_info: Optional[Dict] = None,
) -> Dict[str, Any]:
    """Build a comprehensive project risk explanation."""
    wid = str(work_record.get("work_id", work_record.get("id", "?")))
    evidence = []
    answer_parts = []

    # Basic info
    title = work_record.get("work_description") or work_record.get("activity_name") or work_record.get("title", "Unknown project")
    state = work_record.get("state_name") or work_record.get("state", "")
    const = work_record.get("const_name") or work_record.get("constituency", "")
    mp = work_record.get("mp_name") or work_record.get("mp", "")

    answer_parts.append(f"**Work {wid}**: {title[:150]}")
    if state:
        answer_parts.append(f"📍 Location: {const}, {state}" if const else f"📍 State: {state}")
    if mp:
        answer_parts.append(f"👤 MP: {mp}")

    evidence.append(build_evidence("Project Title", title[:200], "Unified Evaluations", wid))

    # Risk tier
    risk_tier = work_record.get("agency_risk_tier")
    is_high = work_record.get("is_high_risk")
    is_anomaly = work_record.get("is_anomaly")

    risk_label = "HIGH RISK" if is_high else (risk_tier or ("Anomaly Detected" if is_anomaly else "Not flagged"))
    answer_parts.append(f"⚠️ Risk Level: **{risk_label}**")
    evidence.append(build_evidence("Risk Level", risk_label, "Unified Evaluations", wid))

    # Financial signals
    cost_z = work_record.get("cost_z_score")
    if cost_z is not None and abs(cost_z) > 1:
        answer_parts.append(f"💰 Cost Z-Score: {cost_z:.2f} (deviation from comparable projects)")
        evidence.append(build_evidence("Cost Z-Score", f"{cost_z:.2f}", "Unified Evaluations", wid))

    sanction = work_record.get("sanction_amount")
    if sanction:
        evidence.append(build_evidence("Sanction Amount", format_currency(sanction), "Unified Evaluations", wid))

    cost_overrun = work_record.get("cost_overrun_pct")
    if cost_overrun is not None and cost_overrun != 0:
        evidence.append(build_evidence("Cost Overrun", f"{cost_overrun:.1f}%", "Unified Evaluations", wid))

    # Delay signals
    delay = work_record.get("completion_delay_days")
    if delay is not None and delay > 90:
        answer_parts.append(f"⏱️ Completion Delay: {int(delay)} days")
        evidence.append(build_evidence("Completion Delay", f"{int(delay)} days", "Unified Evaluations", wid))

    delay_z = work_record.get("delay_z_score")
    if delay_z is not None and abs(delay_z) > 1:
        evidence.append(build_evidence("Delay Z-Score", f"{delay_z:.2f}", "Unified Evaluations", wid))

    # Agency risk
    agency_score = work_record.get("agency_risk_score_x")
    if agency_score:
        evidence.append(build_evidence("Agency Risk Score", f"{agency_score}", "Unified Evaluations", wid))

    agency_factors = work_record.get("agency_risk_factors", [])
    if agency_factors and isinstance(agency_factors, list):
        for factor in agency_factors[:3]:
            evidence.append(build_evidence("Agency Factor", str(factor)[:200], "Unified Evaluations", wid))

    # FinGuard signals
    if finguard_record:
        fg_score = finguard_record.get("financial_risk_score")
        if fg_score:
            answer_parts.append(f"🔍 Financial Risk Score: {fg_score}")
            evidence.append(build_evidence("Financial Risk Score", str(fg_score), "FinGuard Anomalies", wid))

        reasons = finguard_record.get("anomaly_reasons", [])
        if reasons:
            answer_parts.append("📋 Anomaly Signals:")
            for reason in reasons[:5]:
                answer_parts.append(f"  • {reason}")
                evidence.append(build_evidence("Anomaly Signal", str(reason), "FinGuard Anomalies", wid))

        actions = finguard_record.get("recommended_actions", [])
        if actions:
            answer_parts.append("✅ Recommended Actions:")
            for action in actions[:3]:
                answer_parts.append(f"  • {action}")

    # Cost/delay anomaly signals
    if cost_delay_record:
        severity = cost_delay_record.get("severity_score")
        if severity:
            evidence.append(build_evidence("Severity Score", f"{severity:.2f}", "Cost & Delay Anomalies", wid))

    # Duplicate signals
    if dup_records:
        answer_parts.append(f"🔄 Duplicate Candidate Alerts: {len(dup_records)} pair(s) found")
        for dup in dup_records[:2]:
            other_id = str(dup.get("work_id_B") if str(dup.get("work_id_A")) == wid else dup.get("work_id_A"))
            conf = dup.get("risk_confidence_score", "?")
            evidence.append(build_evidence(
                "Duplicate Candidate",
                f"Paired with work {other_id} (confidence: {conf}%)",
                "Duplicate Project Alerts",
                wid,
            ))

    # Prohibited work flag
    if work_record.get("flag_prohibited_work"):
        answer_parts.append("⛔ Potentially prohibited work under MPLADS guidelines")
        evidence.append(build_evidence("Prohibited Work Flag", "True", "Unified Evaluations", wid))

    answer = "\n".join(answer_parts)

    suggestions = [
        f"Show duplicate alerts for work {wid}",
        f"Show cost anomalies in {const}" if const else "Show top cost anomalies",
        f"Show other high-risk works in {const}" if const else "Show top high-risk projects",
    ]

    return {
        "answer": answer,
        "evidence": evidence,
        "suggestions": suggestions,
        "disclaimer": DISCLAIMER,
    }


# ─── High Risk Projects Response ────────────────────────────────────────────

def build_high_risk_list_response(
    records: List[Dict],
    filters: Dict[str, str],
    snapshot_info: Optional[Dict] = None,
) -> Dict[str, Any]:
    """Build a response listing high-risk projects."""
    if not records:
        filter_desc = ", ".join(f"{k}: {v}" for k, v in filters.items() if v)
        return {
            "answer": f"No high-risk projects found matching the criteria: {filter_desc}" if filter_desc else NO_MATCH_MSG,
            "evidence": [],
            "suggestions": ["Show the top 5 highest-risk projects", "Show high-risk projects in Bihar"],
        }

    evidence = []
    lines = [f"Found **{len(records)}** high-risk project(s):"]

    for i, rec in enumerate(records, 1):
        wid = str(rec.get("work_id", rec.get("id", "?")))
        title = (rec.get("work_description") or rec.get("activity_name") or rec.get("title", ""))[:80]
        state = rec.get("state_name") or rec.get("state", "")
        const = rec.get("const_name") or rec.get("constituency", "")
        cost_z = rec.get("cost_z_score")
        tier = rec.get("agency_risk_tier", "")

        line = f"\n**{i}. Work {wid}** — {title}"
        if state:
            line += f"\n   📍 {const}, {state}" if const else f"\n   📍 {state}"
        if cost_z:
            line += f" | Cost Z: {cost_z:.1f}"
        if tier:
            line += f" | {tier}"

        lines.append(line)
        evidence.append(build_evidence(
            f"High-Risk Project #{i}",
            f"Work {wid}: {title[:60]}",
            "Unified Evaluations",
            wid,
        ))

    answer = "\n".join(lines)
    suggestions = [
        f"Why is work {records[0].get('work_id', '')} high risk?",
        "Show high-risk projects in Madhya Pradesh",
    ]

    return {
        "answer": answer,
        "evidence": evidence,
        "suggestions": suggestions,
        "disclaimer": DISCLAIMER_SHORT,
    }


# ─── Cost/Delay Anomalies Response ──────────────────────────────────────────

def build_anomaly_list_response(
    records: List[Dict],
    anomaly_type: str = "cost_delay",
    filters: Dict[str, str] = None,
) -> Dict[str, Any]:
    """Build a response listing anomalies."""
    filters = filters or {}
    if not records:
        return {
            "answer": "No anomalies found matching the specified criteria.",
            "evidence": [],
            "suggestions": ["Show the top cost anomalies", "Show delayed projects"],
        }

    source = "FinGuard Anomalies" if anomaly_type == "finguard" else "Cost & Delay Anomalies"
    evidence = []
    lines = [f"Found **{len(records)}** anomaly record(s):"]

    for i, rec in enumerate(records, 1):
        wid = str(rec.get("work_id", "?"))
        desc = (rec.get("work_description", "") or "")[:80]
        state = rec.get("state_name", "")
        const = rec.get("const_name", "")
        severity = rec.get("severity_score") or rec.get("financial_risk_score", 0)

        line = f"\n**{i}. Work {wid}** — {desc}"
        if state:
            line += f"\n   📍 {const}, {state}" if const else f"\n   📍 {state}"
        line += f" | Severity: {severity:.1f}" if severity else ""
        delay = rec.get("completion_delay_days")
        if delay and delay > 0:
            line += f" | Delay: {int(delay)} days"

        # Key anomaly flags
        reasons = rec.get("anomaly_reasons", [])
        if reasons:
            line += "\n   Signals: " + "; ".join(str(r) for r in reasons[:3])

        lines.append(line)
        evidence.append(build_evidence(
            f"Anomaly #{i}",
            f"Work {wid}: severity {severity:.1f}" if severity else f"Work {wid}",
            source,
            wid,
        ))

    return {
        "answer": "\n".join(lines),
        "evidence": evidence,
        "suggestions": [
            f"Explain the risk of work {records[0].get('work_id', '')}",
            "Show cost anomalies in Bihar",
        ],
        "disclaimer": DISCLAIMER_SHORT,
    }


# ─── Duplicate Alerts Response ───────────────────────────────────────────────

def build_duplicate_response(
    records: List[Dict],
    target_work_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Build a response for duplicate alerts."""
    if not records:
        if target_work_id:
            return {
                "answer": f"No duplicate candidate alerts found involving work {target_work_id}.",
                "evidence": [],
                "suggestions": ["Show the highest-confidence duplicate candidates"],
            }
        return {
            "answer": "No duplicate candidate alerts found matching the criteria.",
            "evidence": [],
            "suggestions": ["Show the highest-confidence duplicate candidates"],
        }

    evidence = []
    lines = [f"Found **{len(records)}** duplicate candidate alert(s):"]

    for i, rec in enumerate(records, 1):
        wid_a = str(rec.get("work_id_A", "?"))
        wid_b = str(rec.get("work_id_B", "?"))
        conf = rec.get("risk_confidence_score", "?")
        sim = rec.get("text_similarity_score", "?")
        alert_type = rec.get("alert_type", "DUPLICATE")

        desc_a = (rec.get("A_work_description", "") or "")[:60]
        desc_b = (rec.get("B_work_description", "") or "")[:60]

        line = f"\n**{i}. Works {wid_a} ↔ {wid_b}** (Confidence: {conf}%)"
        line += f"\n   Type: {alert_type} | Similarity: {sim}"
        if desc_a:
            line += f"\n   A: {desc_a}"
        if desc_b:
            line += f"\n   B: {desc_b}"

        # Gate flags
        gates = []
        if rec.get("financial_match_flag"):
            gates.append("Financial")
        if rec.get("agency_match_flag"):
            gates.append("Agency")
        if rec.get("temporal_match_flag"):
            gates.append("Temporal")
        if rec.get("location_match_flag"):
            gates.append("Location")
        if gates:
            line += f"\n   Matching gates: {', '.join(gates)}"

        lines.append(line)
        evidence.append(build_evidence(
            f"Duplicate Candidate #{i}",
            f"Works {wid_a} ↔ {wid_b} (confidence: {conf}%)",
            "Duplicate Project Alerts",
            f"{wid_a},{wid_b}",
        ))

    lines.append("\n⚠️ These are *candidate* duplicate alerts, not confirmed duplications. "
                  "Physical verification is required to determine if projects are genuinely duplicated.")

    return {
        "answer": "\n".join(lines),
        "evidence": evidence,
        "suggestions": [
            f"Explain the risk of work {records[0].get('work_id_A', '')}",
            "Show the top 5 highest-confidence duplicate candidates",
        ],
        "disclaimer": "These are candidate duplicate alerts requiring authorized verification. "
                       "Legitimate reasons for similar project descriptions may exist.",
    }


# ─── MP Scorecard Response ──────────────────────────────────────────────────

def build_mp_scorecard_response(record: Dict) -> Dict[str, Any]:
    """Build an MP scorecard summary."""
    mp_name = record.get("mp_name", "Unknown MP")
    mp_id = record.get("mp_id", "?")
    state = record.get("state_name", "")
    const = record.get("const_name", "")
    integrity = record.get("composite_integrity_score")
    total_works = record.get("total_works", 0)
    utilization = record.get("utilization_rate")
    delay = record.get("completion_delay_days")
    anomaly = record.get("is_anomaly")

    evidence = []
    lines = [f"**MP Scorecard: {mp_name}**"]
    if state:
        lines.append(f"📍 {const}, {state}" if const else f"📍 {state}")

    if integrity is not None:
        lines.append(f"🏆 Composite Integrity Score: **{integrity:.1f}/100**")
        evidence.append(build_evidence("Integrity Score", f"{integrity:.1f}", "MP Scorecard Summary", str(mp_id)))

    lines.append(f"📊 Total Works: {total_works}")
    evidence.append(build_evidence("Total Works", str(total_works), "MP Scorecard Summary", str(mp_id)))

    if utilization is not None:
        lines.append(f"💰 Utilization Rate: {utilization:.1%}" if isinstance(utilization, float) and utilization <= 1
                      else f"💰 Utilization Rate: {utilization}")
        evidence.append(build_evidence("Utilization Rate", str(utilization), "MP Scorecard Summary", str(mp_id)))

    if delay is not None:
        lines.append(f"⏱️ Avg Completion Delay: {int(delay)} days")
        evidence.append(build_evidence("Completion Delay", f"{int(delay)} days", "MP Scorecard Summary", str(mp_id)))

    if anomaly:
        lines.append("⚠️ Anomaly flag: Detected")
        evidence.append(build_evidence("Anomaly Flag", "Detected", "MP Scorecard Summary", str(mp_id)))

    return {
        "answer": "\n".join(lines),
        "evidence": evidence,
        "suggestions": [
            f"Show high-risk projects for MP {mp_name.split('(')[0].strip()}" if "(" in mp_name else f"Show high-risk projects for {mp_name}",
            "Which MPs have the highest risk?",
        ],
        "disclaimer": DISCLAIMER_SHORT,
    }


# ─── Compare MPs Response ───────────────────────────────────────────────────

def build_compare_mps_response(records: List[Dict]) -> Dict[str, Any]:
    """Build a comparison of two MPs."""
    if len(records) < 2:
        return {
            "answer": "I need at least two MP names to compare. Please provide both names.",
            "evidence": [],
            "suggestions": [],
        }

    evidence = []
    lines = ["**MP Comparison:**\n"]

    headers = ["Metric"]
    for rec in records[:2]:
        name = rec.get("mp_name", "?")
        headers.append(name.split("(")[0].strip() if "(" in name else name)

    lines.append(" | ".join(headers))
    lines.append("|".join(["---"] * len(headers)))

    metrics = [
        ("Integrity Score", "composite_integrity_score", ".1f"),
        ("Total Works", "total_works", "d"),
        ("Anomaly Flag", "is_anomaly", ""),
    ]

    for label, key, fmt in metrics:
        row = [label]
        for rec in records[:2]:
            val = rec.get(key)
            if val is None:
                row.append("N/A")
            elif fmt == ".1f":
                row.append(f"{val:.1f}")
            elif fmt == "d":
                row.append(str(int(val)))
            else:
                row.append("Yes" if val else "No")
        lines.append(" | ".join(row))

        for rec in records[:2]:
            mp_id = str(rec.get("mp_id", "?"))
            val = rec.get(key)
            evidence.append(build_evidence(label, str(val), "MP Scorecard Summary", mp_id))

    return {
        "answer": "\n".join(lines),
        "evidence": evidence,
        "suggestions": [f"Summarize the scorecard for {records[0].get('mp_name', '').split('(')[0].strip()}"],
        "disclaimer": DISCLAIMER_SHORT,
    }


# ─── Constituency Risk Response ─────────────────────────────────────────────

def build_constituency_response(
    risk_record: Optional[Dict] = None,
    hhi_record: Optional[Dict] = None,
    finguard_record: Optional[Dict] = None,
    geo_record: Optional[Dict] = None,
    constituency_name: str = "",
) -> Dict[str, Any]:
    """Build a constituency risk summary."""
    evidence = []
    lines = [f"**Risk Summary: {constituency_name}**"]

    if risk_record:
        state = risk_record.get("state_name", "")
        if state:
            lines.append(f"📍 State: {state}")
        total = risk_record.get("total_projects", 0)
        high_risk = risk_record.get("high_risk_projects", 0)
        sanctioned = risk_record.get("total_sanctioned", 0)
        spent = risk_record.get("total_spent", 0)

        lines.append(f"📊 Total Projects: {format_number(total)}")
        lines.append(f"⚠️ High-Risk Projects: {format_number(high_risk)} ({(high_risk / total * 100):.1f}%)" if total > 0 else f"⚠️ High-Risk: {high_risk}")
        lines.append(f"💰 Total Sanctioned: {format_currency(sanctioned)}")

        evidence.append(build_evidence("Total Projects", str(total), "Constituency Risk Heatmap", constituency_name))
        evidence.append(build_evidence("High-Risk Projects", str(high_risk), "Constituency Risk Heatmap", constituency_name))
        evidence.append(build_evidence("Sanctioned Amount", format_currency(sanctioned), "Constituency Risk Heatmap", constituency_name))

    if hhi_record:
        hhi = hhi_record.get("hhi")
        dominant = hhi_record.get("dominant_vendor", "")
        dom_share = hhi_record.get("dominant_vendor_share")
        total_vendors = hhi_record.get("total_vendors")

        if hhi is not None:
            hhi_level = "Low" if hhi < 1500 else ("Moderate" if hhi < 2500 else "High")
            lines.append(f"🏢 Vendor Concentration (HHI): {hhi:.0f} ({hhi_level})")
            evidence.append(build_evidence("HHI Score", f"{hhi:.0f} ({hhi_level})", "Constituency HHI", constituency_name))
        if dominant:
            lines.append(f"   Dominant Vendor: {dominant} ({dom_share:.1f}% share)" if dom_share else f"   Dominant Vendor: {dominant}")
            evidence.append(build_evidence("Dominant Vendor", f"{dominant} ({dom_share:.1f}%)" if dom_share else dominant, "Constituency HHI", constituency_name))
        if total_vendors:
            evidence.append(build_evidence("Total Vendors", str(total_vendors), "Constituency HHI", constituency_name))

    if finguard_record:
        ghost_count = finguard_record.get("ghost_count", 0)
        phantom_count = finguard_record.get("phantom_count", 0)
        high_risk_leaks = finguard_record.get("total_high_risk_leaks", 0)
        util = finguard_record.get("utilization_rate")

        if high_risk_leaks:
            lines.append(f"🔍 FinGuard High-Risk Signals: {high_risk_leaks}")
            evidence.append(build_evidence("High-Risk Financial Signals", str(high_risk_leaks), "FinGuard Summary", constituency_name))
        if ghost_count:
            lines.append(f"   Ghost Disbursal Signals: {ghost_count}")
        if util is not None:
            lines.append(f"💰 Utilization Rate: {util:.1%}" if util <= 1 else f"💰 Utilization Rate: {util}")

    if geo_record:
        spatial_risk = geo_record.get("spatial_risk_score")
        cluster_id = geo_record.get("cluster_id")
        if spatial_risk is not None:
            lines.append(f"🗺️ Spatial Risk Score: {spatial_risk:.4f}")
            evidence.append(build_evidence("Spatial Risk Score", f"{spatial_risk:.4f}", "Geospatial Intelligence", constituency_name))
        if cluster_id is not None:
            evidence.append(build_evidence("Geographic Cluster", str(cluster_id), "Geospatial Intelligence", constituency_name))

    if not risk_record and not hhi_record and not finguard_record:
        return {
            "answer": f"Limited data available for constituency '{constituency_name}' in the current analytics snapshot.",
            "evidence": [],
            "suggestions": ["Which constituencies have the most high-risk works?"],
        }

    return {
        "answer": "\n".join(lines),
        "evidence": evidence,
        "suggestions": [
            f"Show high-risk projects in {constituency_name}",
            f"Show vendor concentration in {constituency_name}",
        ],
        "disclaimer": DISCLAIMER_SHORT,
    }


# ─── Vendor Concentration Response ──────────────────────────────────────────

def build_vendor_response(
    network_records: List[Dict],
    hhi_records: Optional[List[Dict]] = None,
) -> Dict[str, Any]:
    """Build a vendor concentration summary."""
    evidence = []
    lines = ["**Vendor Concentration Analysis:**"]

    if network_records:
        lines.append(f"\nTop {len(network_records)} vendors by network risk score:")
        for i, rec in enumerate(network_records, 1):
            name = rec.get("vendor_name", "?")
            score = rec.get("risk_score", 0)
            regions = rec.get("constituencies_operated", 0)
            monopolies = rec.get("monopolies_controlled", 0)
            funds = rec.get("total_funds_captured", 0)

            line = f"\n**{i}. {name}**"
            line += f"\n   Risk Score: {score:.1f} | Constituencies: {regions} | Concentration signals: {monopolies}"
            line += f"\n   Total Funds: {format_currency(funds)}"
            lines.append(line)

            evidence.append(build_evidence(
                f"Vendor #{i}",
                f"{name} — Risk: {score:.1f}, Constituencies: {regions}",
                "Vendor Risk Network",
                name,
            ))

    lines.append("\n⚠️ High vendor concentration is a structural observation. "
                  "It does NOT prove collusion, cartel behaviour, or corruption. "
                  "Verification is required.")

    return {
        "answer": "\n".join(lines),
        "evidence": evidence,
        "suggestions": [
            "What does HHI mean?",
            "Which constituencies have high vendor concentration?",
        ],
        "disclaimer": "Vendor concentration is a structural observation requiring verification. "
                       "It does not prove collusion or corruption.",
    }


# ─── Geospatial Response ────────────────────────────────────────────────────

def build_geospatial_response(
    geo_records: List[Dict],
) -> Dict[str, Any]:
    """Build a geospatial intelligence summary."""
    if not geo_records:
        return {
            "answer": NO_DATA_MSG,
            "evidence": [],
            "suggestions": ["Show risk in Jabalpur"],
        }

    evidence = []
    lines = ["**Geographic Risk Clusters:**"]

    # Group by cluster
    clusters = {}
    for rec in geo_records:
        cid = rec.get("cluster_id", "unknown")
        if cid not in clusters:
            clusters[cid] = []
        clusters[cid].append(rec)

    for cluster_id, members in sorted(clusters.items(), key=lambda x: -max(m.get("spatial_risk_score", 0) for m in x[1]))[:5]:
        top_risk = max(m.get("spatial_risk_score", 0) for m in members)
        names = [m.get("const_name", "?") for m in members[:5]]
        line = f"\n**Cluster {cluster_id}** (Risk: {top_risk:.4f})"
        line += f"\n   Constituencies: {', '.join(names)}"
        lines.append(line)

        for m in members[:3]:
            evidence.append(build_evidence(
                f"Geographic Cluster {cluster_id}",
                f"{m.get('const_name', '?')} — Risk: {m.get('spatial_risk_score', 0):.4f}",
                "Geospatial Intelligence",
                m.get("const_name"),
            ))

    return {
        "answer": "\n".join(lines),
        "evidence": evidence,
        "suggestions": ["Show risk in a specific constituency", "What is a geospatial cluster?"],
        "disclaimer": DISCLAIMER_SHORT,
    }
