"""scoring.py

Modular, explainable risk-scoring engine for the FinGuard analytics module.
Implements:
- Scorer base class and registration pattern
- Scoring components for:
  * Disbursement overruns and actual-amount mismatches using exact-duplicate-adjusted analytical disbursements
  * Robust hierarchical cost benchmarking using robust deviation score terminology
  * Expenditure duplicate event bursts
  * MP-period level vendor concentration
- Generation of evidence-backed natural-language explanations (neutral, objective)
- Temporal category documentation for features
"""

import pandas as pd
import numpy as np
from typing import List, Dict, Optional, Tuple

class RiskSignal:
    """Represents an individual risk signal generated by a component scorer."""
    
    def __init__(self, type_: str, severity: str, evidence: str, value: float, benchmark: Optional[float] = None):
        """
        Temporal Classification:
        - contemporaneous: determined at project startup/sanctioning
        - developmental: accumulated dynamically during project implementation
        - post_completion: determined after final project closing/completion
        """
        self.type = type_
        self.severity = severity  # 'low', 'medium', 'high', 'critical'
        self.evidence = evidence
        self.value = value
        self.benchmark = benchmark

    def to_dict(self) -> Dict:
        return {
            "type": self.type,
            "severity": self.severity,
            "evidence": self.evidence,
            "value": self.value,
            "benchmark": self.benchmark
        }

class ComponentScorer:
    """Abstract base class for modular risk component scorers."""
    
    def __init__(self, name: str, weight: float):
        self.name = name
        self.weight = weight

    def evaluate(self, row: pd.Series) -> Tuple[float, Optional[RiskSignal], Optional[str]]:
        """Evaluates a single work record and returns:
        
        Returns:
            Tuple of (component_score [0-100], optional RiskSignal, optional explanation string)
        """
        raise NotImplementedError

class DisbursementScorer(ComponentScorer):
    """Evaluates financial disbursement overrun and completion discrepancies.
    
    Uses exact-duplicate-adjusted analytical disbursements for overrun scoring.
    Documents data-quality duplicates inflating raw totals.
    
    Temporal classifications of features evaluated:
    - sanction_amount: contemporaneous
    - total_disbursed / analytical_total_disbursed: developmental / post_completion
    - actual_amount: post_completion
    """
    
    def __init__(self, weight: float = 0.35):
        super().__init__("disbursement", weight)

    def evaluate(self, row: pd.Series) -> Tuple[float, Optional[RiskSignal], Optional[str]]:
        ratio = row.get('disbursement_to_sanction_ratio', 0.0)  # duplicate-adjusted analytical ratio
        total_disbursed = row.get('analytical_total_disbursed', 0.0)
        raw_total = row.get('raw_total_disbursed', 0.0)
        sanction_amount = row.get('sanction_amount', 0.0)
        actual_amount = row.get('actual_amount', np.nan)
        work_status = row.get('work_status', '')
        dup_adj = row.get('duplicate_adjustment_amount', 0.0)
        raw_rows = int(row.get('raw_record_count', 0))
        unique_events = int(row.get('unique_event_count', 0))
        
        score = 0.0
        severity = "low"
        evidence_parts = []
        explanation = None
        signal_type = "disbursement"
        
        # 1. Genuine Disbursement overrun (on duplicate-adjusted analytical total)
        if ratio > 1.0:
            pct_over = (ratio - 1.0) * 100.0
            if ratio > 1.2:
                score = 100.0
                severity = "critical"
            else:
                score = ((ratio - 1.0) / 0.2) * 80.0 + 20.0
                severity = "high"
            
            evidence_parts.append(f"exact-duplicate-adjusted analytical disbursement of Rs. {total_disbursed:,.2f} vs sanctioned Rs. {sanction_amount:,.2f} ({pct_over:.1f}% overrun)")
            explanation = f"Recorded exact-duplicate-adjusted analytical disbursement exceeds sanctioned amount by {pct_over:.1f}%."
            
        # 2. Completed project discrepancy check (on duplicate-adjusted analytical total)
        if work_status == 'Completed' and pd.notna(actual_amount) and actual_amount > 0:
            diff = abs(total_disbursed - actual_amount)
            if diff > 5000.0:  # Rs. 5000 tolerance
                # Set score to at least 50 if mismatch exists
                score = max(score, 50.0)
                if severity == "low":
                    severity = "medium"
                
                evidence_parts.append(f"disbursement discrepancy of Rs. {diff:,.2f} vs actual completion cost")
                mismatch_pct = (diff / actual_amount) * 100.0
                mismatch_explanation = f"Discrepancy detected: exact-duplicate-adjusted analytical disbursement does not match final completion amount by {mismatch_pct:.1f}%."
                explanation = explanation + " " + mismatch_explanation if explanation else mismatch_explanation
                
        # 3. Data-quality warning for duplicate inflation
        if dup_adj > 0:
            dq_explanation = (
                f"{raw_rows} raw expenditure records were observed representing {unique_events} exact analytical events. "
                f"Exact duplicate records account for Rs. {dup_adj:,.2f} of the raw recorded total. "
            )
            if np.isclose(total_disbursed, sanction_amount) or total_disbursed == sanction_amount:
                dq_explanation += "The exact-duplicate-adjusted analytical disbursement equals the sanctioned amount."
            elif total_disbursed < sanction_amount:
                dq_explanation += "The exact-duplicate-adjusted analytical disbursement is within the sanctioned amount."
            else:
                dq_explanation += f"The exact-duplicate-adjusted analytical disbursement exceeds the sanctioned amount by {((ratio - 1.0)*100.0):.1f}%."
            
            # If there is no genuine overrun score, add the explanation and a low-severity signal to document the issue
            if score == 0.0:
                explanation = dq_explanation
                signal_type = "disbursement_data_quality"
                evidence_parts.append(f"{raw_rows} raw records, {unique_events} unique events, duplicate adjustment of Rs. {dup_adj:,.2f}")
            else:
                # If there is already an overrun score, append this as context
                explanation = explanation + " " + dq_explanation if explanation else dq_explanation
                evidence_parts.append(f"inflated by Rs. {dup_adj:,.2f} of duplicate records")

        if len(evidence_parts) > 0:
            evidence = ", ".join(evidence_parts)
            signal = RiskSignal(
                type_=signal_type,
                severity=severity,
                evidence=f"Disbursement details: {evidence}",
                value=float(ratio),
                benchmark=1.0
            )
            return score, signal, explanation
            
        return 0.0, None, None

class CostBenchmarkScorer(ComponentScorer):
    """Evaluates works based on robust statistical deviation from peer group medians.
    
    Temporal classifications of features evaluated:
    - sanction_amount: contemporaneous
    - peer benchmark median/MAD (derived from historical database state): historical context
    """
    
    def __init__(self, weight: float = 0.30):
        super().__init__("cost_benchmark", weight)

    def evaluate(self, row: pd.Series) -> Tuple[float, Optional[RiskSignal], Optional[str]]:
        sanction = row.get('sanction_amount', 0.0)
        median = row.get('benchmark_median', 0.0)
        z_score = row.get('robust_z_score', 0.0)
        pct = row.get('benchmark_percentile', 50.0)
        level = row.get('benchmark_level', 'Category National')
        size = row.get('benchmark_sample_size', 0)
        
        if pd.isna(sanction) or sanction <= 0:
            return 0.0, None, None
            
        score = 0.0
        severity = "low"
        
        if z_score > 3.0 or pct > 98.0:
            score = 100.0
            severity = "critical"
        elif z_score > 2.0 or pct > 90.0:
            score = 80.0
            severity = "high"
        elif z_score > 1.0 or pct > 75.0:
            score = 40.0
            severity = "medium"
            
        if score > 0:
            evidence = f"sanction amount Rs. {sanction:,.2f} is in the {pct:.1f}th percentile of peer group (level: {level}, size: {size}, median: Rs. {median:,.2f})"
            explanation = f"Sanction amount is in the {pct:.1f}th percentile of comparable projects (robust deviation score of {z_score:.2f} relative to {level} peer group)."
            
            signal = RiskSignal(
                type_="cost_benchmark",
                severity=severity,
                evidence=evidence,
                value=float(z_score),
                benchmark=float(median)
            )
            return score, signal, explanation
            
        return 0.0, None, None

class DuplicateExpenditureScorer(ComponentScorer):
    """Evaluates patterns of duplicate expenditure event records.
    
    Temporal classifications of features evaluated:
    - identical_payment_burst: developmental
    - duplication_ratio: developmental
    """
    
    def __init__(self, weight: float = 0.20):
        super().__init__("expenditure_duplicate", weight)

    def evaluate(self, row: pd.Series) -> Tuple[float, Optional[RiskSignal], Optional[str]]:
        burst = row.get('identical_payment_burst', 1)
        ratio = row.get('duplication_ratio', 0.0)
        dup_count = row.get('duplicate_record_count', 0)
        
        score = 0.0
        severity = "low"
        
        if burst > 3:
            score = 100.0
            severity = "critical"
        elif burst == 3:
            score = 75.0
            severity = "high"
        elif burst == 2:
            score = 45.0
            severity = "medium"
        elif ratio > 0.2 and dup_count > 0:
            score = 30.0
            severity = "medium"
            
        if score > 0:
            evidence = f"detected identical records burst of size {burst} ({dup_count} total duplicates, duplicate ratio: {ratio*100.0:.1f}%)"
            explanation = f"Detected recurring expenditure records containing identical values: burst size {burst} (duplication ratio: {ratio*100.0:.1f}%)."
            
            signal = RiskSignal(
                type_="expenditure_duplicate",
                severity=severity,
                evidence=evidence,
                value=float(burst),
                benchmark=1.0
            )
            return score, signal, explanation
            
        return 0.0, None, None

class VendorConcentrationScorer(ComponentScorer):
    """Evaluates vendor concentration at the composite MP-period level.
    
    Temporal classifications of features evaluated:
    - vendor_hhi_mp: developmental / post_completion
    - top_vendor_share_mp: developmental / post_completion
    """
    
    def __init__(self, weight: float = 0.15):
        super().__init__("vendor_concentration", weight)

    def evaluate(self, row: pd.Series) -> Tuple[float, Optional[RiskSignal], Optional[str]]:
        hhi = row.get('vendor_hhi_mp', 0.0)
        top_share = row.get('top_vendor_share_mp', 0.0)
        count_mp = row.get('project_count_mp', 0)
        vendor_count = row.get('vendor_count_mp', 0)
        
        # Don't evaluate concentration risk if sample size is too small to be meaningful
        if pd.isna(hhi) or count_mp < 5 or vendor_count < 2:
            return 0.0, None, None
            
        score = 0.0
        severity = "low"
        
        if hhi > 0.6:
            score = 100.0
            severity = "critical"
        elif hhi > 0.4:
            score = 75.0
            severity = "high"
        elif hhi > 0.25:
            score = 40.0
            severity = "medium"
            
        if score > 0:
            evidence = f"MP-period has high vendor concentration: HHI is {hhi:.2f}, with top vendor receiving {top_share*100.0:.1f}% of total funds across {count_mp} works"
            explanation = f"High vendor concentration detected in MP-period: Herfindahl-Hirschman Index (HHI) is {hhi:.2f}, and the largest vendor receives {top_share*100.0:.1f}% of all MP-period disbursements."
            
            signal = RiskSignal(
                type_="vendor_concentration",
                severity=severity,
                evidence=evidence,
                value=float(hhi),
                benchmark=0.25  # HHI > 0.25 represents highly concentrated market
            )
            return score, signal, explanation
            
        return 0.0, None, None

class FinGuardScoringEngine:
    """Coordinates the clean-up, feature extraction, and modular risk scoring pipeline."""
    
    def __init__(self):
        self.scorers: List[ComponentScorer] = []
        # Register default explainable scorers
        self.register_scorer(DisbursementScorer())
        self.register_scorer(CostBenchmarkScorer())
        self.register_scorer(DuplicateExpenditureScorer())
        self.register_scorer(VendorConcentrationScorer())

    def register_scorer(self, scorer: ComponentScorer):
        """Enables dynamic component registration (e.g. adding new models later)."""
        self.scorers.append(scorer)

    def compute_risk_scores(self, works_df: pd.DataFrame) -> pd.DataFrame:
        """Processes each work row, applies active scorers, and computes combined scores.
        
        Args:
            works_df: Enriched works DataFrame containing all features and benchmarks.
            
        Returns:
            DataFrame with finguard risk score and band columns added.
        """
        scores = []
        bands = []
        signals_payload = []
        explanations_payload = []
        
        for idx, row in works_df.iterrows():
            total_weight = 0.0
            weighted_score_sum = 0.0
            row_signals = []
            row_explanations = []
            
            for scorer in self.scorers:
                score, signal, explanation = scorer.evaluate(row)
                
                # Accumulate score and weight
                weighted_score_sum += score * scorer.weight
                total_weight += scorer.weight
                
                if signal:
                    row_signals.append(signal.to_dict())
                if explanation:
                    row_explanations.append(explanation)
            
            # Compute weighted final score
            final_score = (weighted_score_sum / total_weight) if total_weight > 0 else 0.0
            final_score = int(round(final_score))
            
            # Determine risk band
            if final_score >= 90:
                band = "Critical"
            elif final_score >= 70:
                band = "High"
            elif final_score >= 40:
                band = "Medium"
            else:
                band = "Low"
                
            scores.append(final_score)
            bands.append(band)
            signals_payload.append(row_signals)
            explanations_payload.append(row_explanations)
            
        result_df = works_df.copy()
        result_df['finguard_risk_score'] = scores
        result_df['finguard_risk_band'] = bands
        result_df['finguard_signals'] = signals_payload
        result_df['finguard_explanations'] = explanations_payload
        
        return result_df
